POST https://15-09.onrender.com/register HTTP/1.1
Content-Type: application/json

{
    "name":"Júlio",
    "email":"jcesarddiniz05@gmail.com",
    "password":"1234"
}
############################

POST https://15-09.onrender.com/login HTTP/1.1
Content-Type: application/json

{
    "email":"jcesarddiniz05@gmail.com",
    "password":"1234"
}
